import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  title: {
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 8,
  },

  container: {
    flex: 1,
    backgroundColor: "black",
  },
  headerSection: {
    position: "relative",
  },
  heroCard: {
    paddingHorizontal: 20,
    paddingBottom: 12,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    height: "100%",
    // overflow: "hidden",
    paddingTop: 40,
  },
  heroContent: {
    flex: 1,
    // position: "relative",
    paddingTop: Platform.OS === "ios" ? 30 : 0,
  },
  heroLeft: {
    flex: 1,
  },
  welcomeTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#E5E7EB",
    marginBottom: 4,
  },
  subMuted: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 6,
  },
  subDetails: {
    fontSize: 12,
    color: "rgba(209,213,219,0.9)",
    marginBottom: 2,
  },
  heroImage: {
    width: 280,
    height: 400,
    position: "absolute",
    right: -40,
    top: 20,
  },
  statsCard: {
    marginHorizontal: 20,
    // marginTop: -40,
  },
  glassStats: {
    padding: 16,
  },
  statsText: {
    fontSize: 14,
    color: "#fff",
    marginBottom: 12,
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  goalText: {
    fontSize: 12,
    color: "#9CA3AF",
    width: 70,
  },
  progressBar: {
    flex: 1,
    height: 8,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 4,
    overflow: "hidden",
    position: "relative",
  },
  progressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#4ADE80",
    borderRadius: 4,
  },
  progressThumb: {
    position: "absolute",
    left: "50%",
    top: -2,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#fff",
    marginLeft: -6,
  },
  targetWeight: {
    fontSize: 12,
    color: "#fff",
    width: 40,
    textAlign: "right",
  },
  focusButton: {
    marginHorizontal: 20,
    marginTop: 16,
  },
  focusGlass: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  focusText: {
    flex: 1,
    fontSize: 16,
    color: "#fff",
    fontWeight: "500",
  },
  section: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  sectionCard: {
    padding: 20,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#fff",
  },
  caloriesRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    marginBottom: 16,
  },
  calorieCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 6,
    borderColor: "rgba(74, 222, 128, 0.6)",
  },
  calorieCircleInner: {
    alignItems: "center",
  },
  calorieNumber: {
    fontSize: 24,
    fontWeight: "700",
    color: "#fff",
  },
  calorieLabel: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 2,
  },
  calorieInfo: {
    flex: 1,
  },
  calorieSummary: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
  },
  calorieLeft: {
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: 4,
  },
  mealLogBtn: {
    marginTop: 12,
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  mealLogText: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "500",
  },
  mealBar: {
    flexDirection: "row",
    height: 8,
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 8,
  },
  mealSegment: {
    flex: 1,
  },
  breakfast: { backgroundColor: "#4ADE80" },
  lunch: { backgroundColor: "#FB923C" },
  dinner: { backgroundColor: "#F87171" },
  snack: { backgroundColor: "rgba(255,255,255,0.2)" },
  mealLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  mealLabel: {
    fontSize: 12,
    color: "#9CA3AF",
  },
  targetRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  targetText: {
    fontSize: 14,
    color: "#fff",
  },
  mealScroll: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  mealCard: {
    width: 140,
    marginRight: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  mealTimeBadge: {
    backgroundColor: "#4ADE80",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    alignSelf: "flex-start",
    marginBottom: 8,
  },
  mealTime: {
    fontSize: 11,
    color: "#0F172A",
    fontWeight: "600",
  },
  mealImagePlaceholder: {
    width: "100%",
    height: 80,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 8,
    marginBottom: 8,
  },
  mealType: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "600",
  },
  mealKcal: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 4,
  },
  viewPlanBtn: {
    backgroundColor: "#0EA5E9",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  viewPlanText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
});
